# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8627f6a69dc64511fd9d32def510ec22cd21e6e62a28b1706ad747f518fda565189c1d089cc8002c451165d0449333db11ee8c181d43050cac419e03bebf0a79

test:
  secret_key_base: 4bd9e78d19e4707147df559de22a5098f3b0dab7e6db69bef88a13c713b4c0e46d49a7d4967bb666d6c603db5aa9999e0e5afc55b0fbba77383c7c7a522fbab4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
